name: 'Add Unified CI to new Go repos'
description: 'Add Unified CI to newly created Go repositories'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token to use with GitHub API'
    required: true
outputs:
  all:
    description: 'A list of Go repositories without Unified CI'
  new:
    description: 'A list of new Go repositories without Unified CI'
  pr:
    description: 'A link to the PR that adds Unified CI to new Go repositories'
runs:
  using: 'node16'
  main: 'dist/index.js'
