on:
  pull_request:
  push:
    branches: ${{{ .github.protected_branches + [.github.default_branch] | unique }}}
name: Go Checks

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-check:
    uses: protocol/.github/shared/.github/workflows/go-check.yml@v1.0
