on:
  pull_request:
  push:
    branches: ${{{ .github.protected_branches + [.github.default_branch] | unique }}}
name: Go Test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: protocol/.github/shared/.github/workflows/go-test.yml@${{{ source.tag | split("-") | [(.[0] | split(".") | .[0:2] | join(".")), (.[1:])] | flatten | join("-") }}}
