on:
  pull_request:
  push:
    branches: ${{{ .github.protected_branches + [.github.default_branch] | unique }}}
name: Go Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: protocol/.github/.github/workflows/go-test.yml@v1.0
    with:
      go-versions: '${{{ config.go.versions }}}'
