name: test & maybe release
on:
  push:
    branches:
      - ${{{ github.default_branch }}}
  pull_request:

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  js-test-and-release:
    uses: protocol/.github/shared/.github/workflows/js-test-and-release.yml@v1.0
