name: Release Checker
on:
  pull_request:
    paths: [ 'version.json' ]

jobs:
  release-check:
    uses: protocol/.github/.github/workflows/release-check.yml@master
    with:
      go-version: ${{{ config.go.versions[-1] }}}
