name: Release Checker
on:
  pull_request_target:
    paths: [ 'version.json' ]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-check:
    uses: protocol/.github/shared/.github/workflows/release-check.yml@v1
