name: Sync github release assets with dist.ipfs.io
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-github-and-dist-ipfs-io:
    uses: protocol/.github/.github/workflows/sync-release-assets.yml@master
    with:
      dist: ${{{ config.dist }}}
