name: Tag Push Checker
on:
  push:
    tags:
      - v*

permissions:
  contents: read
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: protocol/.github/shared/.github/workflows/tagpush.yml@v1
