name: Tag Push Checker
on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  releaser:
    uses: protocol/.github/.github/workflows/tagpush.yml@master
