name: copy workflow versioning
description: Copy workflow steps specific to versioning

runs:
  using: "composite"
  steps:
    - name: add version.json file (in order to deploy versioning workflows)
      if: hashFiles(format('{0}/version.json', env.TARGET_REPO_DIR)) == ''
      working-directory: ${{ env.TARGET_REPO_DIR }}
      shell: bash
      run: |
        git fetch origin --unshallow # we need the entire commit history
        version=$(git describe --tags --abbrev=0 || true) # highest released version on current branch
        printf '{"version": "%s"}' "$version" | jq . > version.json
        git add version.json
        git commit -m "add version.json file"
