name: Add Unified CI to new Go repositories
on:
  - push
  - workflow_dispatch

jobs:
  find-and-add:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/add-unified-ci-to-go-repos
        with:
          GITHUB_TOKEN: ${{ secrets.WEB3_BOT_GITHUB_TOKEN }}
