name: Add Unified CI to new Go repositories
on:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week
  workflow_dispatch:

jobs:
  add-unified-ci-to-new-go-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/add-unified-ci-to-new-go-repos
        with:
          GITHUB_TOKEN: ${{ secrets.WEB3_BOT_GITHUB_TOKEN }}
