on:
  pull_request:
    paths:
      - 'configs/*.json'

name: Check Config

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check if config files are sorted alphabetically
        run: |
          for config in configs/*.json; do
            echo "::group::$config"
            .github/workflows/check-config.sh $config
            echo "::endgroup::"
          done
