name: Releaser
on: [ workflow_call ]

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Determine version
        run: echo "version=$(jq -r .version version.json)" >> $GITHUB_OUTPUT
      - id: branch
        name: Determine branch
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: echo "default=refs/heads/$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
      - name: Determine if this commit is a merged PR (if we're not on a default branch)
        if: steps.branch.outputs.default != github.ref
        id: getmergedpr
        uses: actions-ecosystem/action-get-merged-pull-request@59afe90821bb0b555082ce8ff1e36b03f91553d9
        with:
          github_token: ${{ github.token }}
      - id: label
        name: Check if the "release" label was set on the PR
        if: steps.getmergedpr.outputs.number != '' && steps.branch.outputs.default != github.ref
        env:
          LABELS: ${{ steps.getmergedpr.outputs.labels }}
        run: |
          while IFS= read -r label; do
            if [[ "$label" == "release" ]]; then
              echo "release=true" >> $GITHUB_OUTPUT
              break
            fi
          done <<< "$LABELS"
      - name: Create release
        if: steps.branch.outputs.default == github.ref || steps.label.outputs.release == 'true'
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          git fetch origin --tags
          if ! $(git rev-list "$VERSION.." &> /dev/null); then
            git tag "$VERSION"
            git push --tags
          fi
