name: Releaser
on: [ workflow_call ]

jobs:
  releaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        name: Determine version
        run: echo "version=$(jq -r .version version.json)" >> $GITHUB_OUTPUT
      - id: pr
        name: Determine if this commit is a merged PR (if we're not on a default branch)
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
        uses: actions-ecosystem/action-get-merged-pull-request@59afe90821bb0b555082ce8ff1e36b03f91553d9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - id: labels
        env:
          LABELS: ${{ steps.pr.outputs.labels }}
        run: echo "labels=$(jq -nc 'env.LABELS | split("\n")')" >> $GITHUB_OUTPUT
      - name: Create release
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) ||
          contains(fromJSON(steps.labels.outputs.labels), 'release')
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          draft: false
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
