name: Release
on:
  push:
    paths: [CHANGELOG.md]
    branches: [master, release/*]
  pull_request:
    paths: [CHANGELOG.md]
    branches: [master, release/*]
jobs:
  release:
    name: Realase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: release
        uses: pl-strflt/changelog-driven-release@v1
        with:
          path: CHANGELOG.md
          draft: ${{ github.event_name == 'pull_request' }}
      - if: github.event_name == 'push' && steps.release.outputs.tag != ''
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          RELEASE_TAG: ${{ steps.release.outputs.tag }}
        run: gh api repos/$GITHUB_REPOSITORY/refs/heads/release/$RELEASE_TAG || gh api -X POST repos/$GITHUB_REPOSITORY/refs -f ref=refs/heads/release/$RELEASE_TAG -f sha=$RELEASE_TAG
      - if: github.event_name == 'pull_request' && steps.release.outputs.tag != ''
        uses: marocchino/sticky-pull-request-comment@3d60a5b2dae89d44e0c6ddc69dd7536aec2071cd # v2.5.0
        with:
          header: release
          recreate: true
          message: |
            ## [${{ steps.release.outputs.tag }}](${{ steps.release.outputs.url }})

            ${{ steps.release.outputs.body }}
